name: Run test

on:
  workflow_call:
    inputs:

      command:
        required: false
        type: string
        default: 'test'

      node-version:
        required: false
        type: string
        default: '16'

      pnpm-version:
        required: false
        type: string
        default: '6'

      package:
        required: false
        type: string

      publish-coverage:
        required: false
        type: boolean
        default: true

    secrets:

      codecov_token:
        required: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ inputs.pnpm-version }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - run: pnpm install

      - name: Run script
        run: |
          if [ "${{ inputs.package }}" == "" ];
            then pnpm ${{ inputs.command }} -r
            else pnpm -C packages/${{ inputs.package }} ${{ inputs.command }}
          fi

      - name: Publish-coverage
        if: ${{ inputs.publish-coverage }}
        run: pnpm exec codecov --token=${{ secrets.codecov_token }}